#!/bin/bash
#SBATCH --job-name=fesom2.0_INI
#SBATCH --partition=standard96
#SBATCH --ntasks=2304      ######2304
#SBATCH --ntasks-per-node=96
#SBATCH --time=00:30:00
#SBATCH -o slurm-out.out
#SBATCH -e slurm-err.out
#SBATCH --account=hbk00087 

## modules HLRN
module purge
module load slurm
module load HLRNenv
module load sw.skl
module load cmake
module load cdo nco 
#module load intel/19.0.5
#module load impi/2019.5
module load intel/18.0.6
module load impi/2018.5
export PSM2_MULTI_EP=0

set -x

ulimit -s unlimited

# determine JOBID
JOBID=`echo $SLURM_JOB_ID |cut -d"." -f1`

ln -s ../../bin/fesom_ini.x
#ln -s ../../bin/fesom.x .           # cp -n ../bin/fesom.x
#cp -n ../config/namelist.config  .
#cp -n ../config/namelist.forcing .
#cp -n ../config/namelist.oce     .
#cp -n ../config/namelist.ice     .
#cp -n ../config/namelist.io     .

date
srun --mpi=pmi2 ./fesom_ini.x > "fesom2.0.out"
date

# qstat -f $PBS_JOBID

#export EXITSTATUS=$?
#if [ ${EXITSTATUS} -eq 0 ] || [ ${EXITSTATUS} -eq 127 ] ; then
#sbatch job.ll_ollie
#fi#
